septic/customers/urls.py
from django.urls import path

from . import views


app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('edit/<int:option>/', views.edit, name="edit")
]

septic/septic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('customers/', include('customers.urls')),
    path('employees/', include('employees.urls')),
    path('', views.group_redirect, name='home'),
    path('fullcalendar/', include('fullcalendar.urls')),
    path('workorder/', include('workorder.urls')),
]

septic/customers/models.py
from django.db import models



class Customer(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.PROTECT)
    zip_code = models.IntegerField(default=00000, null=True)
    address = models.CharField(max_length=50, blank=True, null=True)
    emergency = models.CharField(max_length=255, blank=True, null=True)

septic/customers/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .models import Customer
from django.urls import reverse

def index(request):
    user = request.user

    if not Customer.objects.filter(user_id=user.id).exists():
        return redirect('create/')
    else:
        specific_customer = Customer.objects.get(user_id=user.id)
        context = {
            'user': user,
            'specific_customer': specific_customer
        }
        print(user)
        return render(request, 'customers/index.html', context)


def create(request):
    if request.method == 'POST':
        user = request.user
        name = request.POST.get('name')
        address = request.POST.get('address')
        zip_code = request.POST.get('zip_code')
        new_customer = Customer(
            user_id=request.user.id,
            name=name,
            address=address,
            zip_code=zip_code,
        )
        new_customer.save()
        return HttpResponseRedirect(reverse('customers:index'))
    else:
        return render(request, 'customers/create.html')


def edit(request, option):
    specific_option = option
    user = request.user
    specific_customer = Customer.objects.get(user_id=user.id)
    context = {
        'specific_customer': specific_customer,
        'specific_option': specific_option
    }
    if request.method == 'POST':
        if specific_option == 2:
            specific_customer.name = request.POST.get('name')
            specific_customer.address = request.POST.get('address')
            specific_customer.zip_code = request.POST.get('zip_code')
            specific_customer.save()

        return HttpResponseRedirect(reverse('customers:index'))
    else:
        return render(request, 'customers/edit.html', context)

def emergency(request, option):
    specific_option = option
    user = request.user
    specific_customer = Customer.objects.get(user_id=user.id)
    context = {
        'specific_customer': specific_customer,
        'specific_option': specific_option
    }
    if request.method == 'POST':
        if specific_option == 1:
            specific_customer.name = request.POST.get('name')
            specific_customer.address = request.POST.get('address')
            specific_customer.zip_code = request.POST.get('zip_code')
            specific_customer.emergency = request.POST.get('emergency')
            specific_customer.save() 

septic/customers/templates/customers/create.html
{% extends 'base.html' %}
{# This top line allows this template to utilizing the styling and layout from the base. All your templates should do the same. #}

{% block title %} Customer Account {% endblock %}

{% block header %}<h1 class="display-1 text-center" id="title">Create Account</h1> {% endblock %}

{% block content %}
<div class="row row-cols-auto d-flex justify-content-center">
  <div class="col"></div>
  <div class="col">
    <div class="mb-3">
      <form class="form-control" action="{% url 'customers:create' %}" method="POST">
        {% csrf_token %}
        Name:<input class="form-control" type="text" name="name" id="name"><br>
        Address:<input  class="form-control" type="text" name="address" id="address"><br>
        Zip Code:<input class="form-control" type="text" name="zip_code" id="zip_code"><br>
        <input type="submit" class="form-control" value="Create Account">
      </form>
    </div>
  </div>
  <div class="col-3"></div>
</div>
{% endblock %}

septic/customers/templates/customers/edit.html
{% extends 'base.html' %}
{# This top line allows this template to utilizing the styling and layout from the base. All your templates should do the same. #}

{% block title %}
  {% if specific_option == 1 %}
    Emergency Form
  {% elif specific_option == 2 %}
    Edit Account Info
  {% endif %}
{% endblock %}

{% block header %}
  {% if specific_option == 1 %}
    <h1 class="display-1 text-center" id="title">Emergency Form</h1>
  {% elif specific_option == 2 %}
    <h1 class="display-1 text-center" id="title">Edit Account Info</h1>
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row row-cols-auto d-flex justify-content-center">
    <div class="col"></div>
    <div class="col"> 
      <div class="mb-3">
        {% if specific_option == 1 %}
        <form action="{% url 'customers:edit' 1 %}" method="POST">
          {% csrf_token %}
            <p class="display-5 text-center" style="text-decoration:underline;">Name</p>
            <input type="text" class="form-control" name="name" id="name" value="{{specific_customer.name}}"><br>
            <p class="display-5 text-center" style="text-decoration:underline;">Address</p>
            <input type="text" class="form-control" name="address" id="address" value="{{specific_customer.address}}"><br>
            <p class="display-5 text-center" style="text-decoration:underline;">Zip Code</p>
            <input type="text" class="form-control" name="zip_code" id="zip_code" value='{{ specific_customer.zip_code }}'><br>
            <p class="display-5 text-center" style="text-decoration:underline;">Describe Emergency</p>
            <input type="text" class="form-control" name="emergency" id="emergency" value='{{ specific_customer.emergency }}'><br>
            <input type="submit" class="form-control" value="Submit">
          </form>
        {% elif specific_option == 2 %}
        <form action="{% url 'customers:edit' 2 %}" method="POST">
        {% csrf_token %}
          <p class="display-5 text-center" style="text-decoration:underline;">Name</p>
          <input type="text" class="form-control" name="name" id="name" value="{{specific_customer.name}}"><br>
          <p class="display-5 text-center" style="text-decoration:underline;">Address</p>
          <input type="text" class="form-control" name="address" id="address" value="{{specific_customer.address}}"><br>
          <p class="display-5 text-center" style="text-decoration:underline;">Zip Code</p>
          <input type="text" class="form-control" name="zip_code" id="zip_code" value='{{ specific_customer.zip_code }}'><br>
          <input type="submit" class="form-control" value="Update Account">
        </form>
        {% endif %}
      </div>
    </div>
    <div class="col"></div>
  </div>
{% endblock %}

septic/customers/templates/customers/index.html
{% extends 'base.html' %}
{# This top line allows this template to utilizing the styling and layout from the base. All your templates should do
the same. #}

{% block title %} Customers Home {% endblock %}
{% block header %} <h1 class="display-1 text-center" id="title">Customers Home</h1> {% endblock %}

{% block content %}
  <div class="row row-cols-auto d-flex justify-content-center">
    {% if user.is_authenticated %}
    <div class="col"></div>
    <div class="col" id="custom-table">
      <h1 class="display-3 text-center" id="subtitle">Hello, {{ user.username }}</h1>
      <table class="table table-striped table-hover table-light">
        <caption style="color:whitesmoke;font-size:.75rem;">Profile Details</caption>
        <ul>
          <li>Septic Inspection - $195</li>
          <li>Drainfield Inspection - $125</li>
          <li>Drainfield Rejuvenation - Bid</li>
          <li>County Filing Fee - $55</li>
        </ul>
        <tbody>
          <tr>
            <th>Name</th> 
            <td>{{ specific_customer.name }}</td>
          </tr>
          <tr>
            <th>Address</th>
            <td>{{ specific_customer.address }}</td>
          </tr>
          <tr>
            <th>Zip Code</th>
            <td>{{ specific_customer.zip_code }}</td>
          </tr>
        </tbody>
      </table>
    <div class="col-4"></div>
      {% endif %}
  </div>
{% endblock %}