septic/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

septic/customers/urls.py
from django.urls import path

from . import views


app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('edit/<int:option>/', views.edit, name="edit")
]

septic/employees/urls.py
from django.urls import path, include
from . import views


app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
]

septic/septic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('customers/', include('customers.urls')),
    path('employees/', include('employees.urls')),
    path('', views.group_redirect, name='home'),
    path('fullcalendar/', include('fullcalendar.urls')),
    path('workorder/', include('workorder.urls')),
]

septic/workorder/urls.py
from django.urls import path, include
from . import views


app_name = "workorder"
urlpatterns = [
    path('workorder/', views.create, name='create'),
]

septic/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
        rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
        crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'stylesheet.css' %}">
  <title>{% block title %}{% endblock %}</title>
</head>
  <body>

  {% if user.is_authenticated %}
    {% for group in user.groups.all%}
      {% if group.name == "Customers" %}
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">A Septic Company</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
                  aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'customers:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'customers:edit' 1 %}">Emergency Form</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'customers:edit' 2 %}">Edit Account Info</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'fullcalendar:calendar' %}">View Current Jobs</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      {% elif group.name == "Employees" %}
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">A Septic Company</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
                  aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'employees:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'fullcalendar:calendar' %}">Job Board</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'workorder:create' %}">Create Work Order</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      {% endif %}
    {% endfor %}
  {% endif %}
  <div class="container d-flex justify-content-center">
    <main>
      <h1>{% block header %} {% endblock %}</h1>
      {% block content %} {% endblock %}
    </main>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
            integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
            integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
            crossorigin="anonymous"></script>
  </body>
</html>

septic/templates/home.html
{% extends 'base.html' %}

{% block title %} Home Portal {% endblock %}

{% block header %}
    <h1 class="display-1 text-center" id="title">Welcome to A Septic Company!</h1>
{% endblock %}

{% block content %}
<div class="row row-cols-auto d-flex justify-content-center">
  <div class="col">
    <div class="col"></div>
    <div class="col" id="custom-table">
    {% if user.is_authenticated %}
      <p class="display-6 text-center" id="subtitle">Hello {{ user.username }}. You don't have a group assigned.</p>
      <p class="display-6 text-center" id="subtitle">Please contact administrator or attempt to register again.</p>
      <p><a href="{% url 'logout' %}"><button class="form-control">Log Out</button></a></p>
    {% else %}
      <p class="display-6 text-center" id="subtitle">You are not logged in</p>
      <p class="display-6 text-center" id="subtitle">Please log in or create an account</p>
      <a href="{% url 'login' %}"><button class="form-control"><p>Log In</p></button></a>
      <a href="{% url 'accounts:register' %}"><button class="form-control"><p>Sign Up</p></button></a>
    {% endif %}
    </div>
  <div class="col"></div>
</div>
{% endblock %}