septic/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

septic/employees/urls.py
from django.urls import path, include
from . import views


app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
]

septic/septic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('customers/', include('customers.urls')),
    path('employees/', include('employees.urls')),
    path('', views.group_redirect, name='home'),
    path('fullcalendar/', include('fullcalendar.urls')),
    path('workorder/', include('workorder.urls')),
]

septic/employees/models.py
from django.db import models

class Employees(models.Model):
    name = models.CharField(max_length=50, default="")
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.PROTECT)
    zip_code = models.IntegerField(default=00000, null=True)

septic/employees/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Employees
from django.apps import apps


def create(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        zip_code = request.POST.get('zip_code')
        new_employee = Employees(
            user_id=request.user.id,
            name=name,
            zip_code=zip_code
        )
        new_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        return render(request, 'employees/create.html')

def index(request):
    user = request.user
    if not Employees.objects.filter(user_id=user.id).exists():
        return redirect('create/')
    else:
        specific_employee = Employees.objects.get(user_id=user.id)
        specific_employee.save()
        context = {
            'user': user,
            'specific_employee': specific_employee
        }
        return render(request, 'employees/index.html', context)

septic/employees/templates/employees/create.html
{% extends 'base.html' %}

{% block title %} Employee Account {% endblock %}

{% block header %}<h1 class="display-1 text-center" id="title">Create Account</h1>{% endblock %}

{% block content %}
<div class="row row-cols-auto d-flex justify-content-center">
  <div class="col"></div>
  <div class="col">
    <div class="mb-3">
      <form class="form-control" action="{% url 'employees:create' %}" method="POST">
      {% csrf_token %}
      Name:<input class="form-control" type="text" name="name" id="name"><br>
      Zip Code:<input class="form-control" type="text" name="zip_code" id="zip_code"><br>
      <input class="form-control" type="submit" value="Create Account">
    </form>
    </div>
  </div>
  <div class="col"></div>
</div>
{% endblock %}

septic/employees/templates/employees/index.html
{% extends 'base.html' %}

{% block title %}Employee Home{% endblock %}
{% block header %} <h1 class="display-1 text-center" id="title">Employee Home</h1> {% endblock %}

{% block content %}

  {% if user.is_authenticated %}
  <div class="row row-cols-auto d-flex justify-content-center">
    <div class="col"></div>
    <div class="col" id="custom-table">
      <h1 class="display-3 text-center" id="subtitle">Hello, {{ user.username }}!</h1>
  {% else %}
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
    {% endif %}

{% endblock %}